/**
 * Generates shared/species-catalog.json from the compact table below.
 * Run with: npx tsx shared/scripts/build-species-catalog.ts
 * Colours and body proportions are stylised for the 3D scenes; they are not field-guide accurate.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import type { Archetype, CatalogSpecies, SpeciesGroup } from '../src/types';

type Pal = [back: string, side: string, belly: string, fin: string];
const PAL: Record<string, Pal> = {
  olive: ['#4d6a36', '#8aa457', '#e5e2c2', '#6a8247'],
  bronze: ['#5e4a26', '#9a8040', '#ddd2a4', '#7d5f30'],
  sunny: ['#3f5f66', '#6f9a78', '#ee9a3a', '#5a7e86'],
  ember: ['#6b6a2f', '#d49a3a', '#e4662e', '#a8742c'],
  silver: ['#5d7890', '#b8c7d0', '#f1f3f2', '#9fb0ba'],
  steel: ['#3f5468', '#8ea3b2', '#e8ecec', '#6f8596'],
  gold: ['#8a6a1e', '#d6b04a', '#f2e4b0', '#c08a2c'],
  mud: ['#514a33', '#7d7252', '#c9bf9c', '#6a5e3e'],
  slate: ['#3a4148', '#5f6b73', '#a9b1b3', '#4b555c'],
  pike: ['#3f5a34', '#7a8f4a', '#dcd8b4', '#7d6a3a'],
  rainbow: ['#5b7260', '#c9b7bd', '#eef0ea', '#8e9c8d'],
  brown: ['#574a2a', '#8f7a48', '#e5d9b2', '#7a5f34'],
  lake: ['#4a5f66', '#9aa9ac', '#eef1ee', '#77868a'],
  salmon: ['#4c5b6a', '#b9757a', '#e7d8d2', '#8e5257'],
  char: ['#3d4b40', '#6d8170', '#f0a24b', '#d4603a'],
  catfish: ['#3c3f43', '#6b6f70', '#d8d6c7', '#4b4f52'],
  carp: ['#6a5a2a', '#c09a48', '#e8d9a0', '#a9793a'],
  sturgeon: ['#3a3b38', '#6d6a5a', '#d9d4c0', '#55534a'],
  gar: ['#4a5a3a', '#8c9660', '#e3dfc1', '#6c7750'],
  eel: ['#2f3a2f', '#56604c', '#b8b98f', '#414a3b'],
  lamprey: ['#4a4a3c', '#8a8670', '#d8d3b8', '#615e4a'],
  shad: ['#3a5a7a', '#b5c4cf', '#f3f4f2', '#90a6b7'],
  dace: ['#6b5a34', '#c8b37a', '#ece3c4', '#b56a3a'],
  darter: ['#6a5a2c', '#b09a52', '#e6d9a8', '#c2562d'],
  sculpin: ['#4c4233', '#7a6a4c', '#bbb092', '#5d5038'],
  killifish: ['#687a4c', '#b9c08a', '#f0eccd', '#9aa66a'],
  stickleback: ['#5a6a48', '#a7b07c', '#e9e6c4', '#8f9a64'],
  striper: ['#3c5268', '#9db3c0', '#eef2f1', '#7c93a3'],
  drum: ['#5b5f66', '#a4a9a9', '#e9eae6', '#7a8084'],
  newt: ['#5d4a2a', '#8b6a34', '#e38a2c', '#6d5530'],
  frog: ['#4d6b2f', '#7fa043', '#d9dcae', '#66803a'],
  bullfrog: ['#55692e', '#88974a', '#d6d8ae', '#6b7a3c'],
  leopard: ['#6a7a3a', '#a7a15a', '#e8e4c0', '#8a8a4a'],
  turtleG: ['#3f4b2a', '#58683a', '#c9c38b', '#6c7a48'],
  turtleP: ['#2f3a2a', '#4a5a38', '#d7c36a', '#c2452f'],
  turtleB: ['#4a4336', '#6d6450', '#c7bc96', '#57503f'],
  crayO: ['#7a3a2a', '#a8523a', '#d98e6a', '#8a3f2c'],
  crayG: ['#4a4a2a', '#7a7a42', '#b7b27a', '#5d5d34'],
  crayR: ['#8a2a1e', '#b9412c', '#dd8d6c', '#9a3422'],
  crabB: ['#3a5d82', '#5a84a8', '#e6e0d0', '#d9532e'],
  crabG: ['#3f5a36', '#6a8452', '#cfc7a2', '#5a7446'],
  mussel: ['#2f2d2a', '#4d4a43', '#8a8474', '#3a3833'],
  musselZ: ['#6b5a3a', '#b9a66a', '#e8ddb8', '#8a7444'],
  clam: ['#8a7a4a', '#c9b97a', '#ece4c2', '#a9965a'],
  snail: ['#6a563a', '#8f7650', '#cdbb94', '#7d6643'],
  oyster: ['#6d6a60', '#9f9c8e', '#dcd8c6', '#85826f'],
  mammalB: ['#4a3826', '#6e5236', '#a8896a', '#58422c'],
  mammalG: ['#5e6164', '#8b8f92', '#b8bbbc', '#707477'],
  mammalO: ['#3f3126', '#5e4632', '#a48968', '#4a3a2c'],
  plantG: ['#2f6a34', '#4f9a4a', '#9cc77a', '#3d8040'],
  plantL: ['#2e6a3c', '#4a9a5a', '#e8c2d8', '#3a8048'],
  plantY: ['#4a6a2a', '#7aa443', '#d8c83a', '#5d8a34'],
  plantM: ['#37602f', '#5d8f45', '#a4c77c', '#46733a'],
  algae: ['#2f6a4a', '#3fae74', '#9fd9a4', '#2f8a5a'],
};

type Row = [
  sci: string,
  common: string,
  family: string,
  group: SpeciesGroup,
  arch: Archetype,
  len: [number, number],
  pal: keyof typeof PAL,
  pattern: 'bars' | 'spots' | 'stripe' | 'mottled' | 'none',
  band: CatalogSpecies['depthBand'],
  school: 0 | 1,
  temp?: [number, number],
  iucn?: CatalogSpecies['iucn'],
  notes?: string,
];

const ROWS: Row[] = [
  // Centrarchidae
  [
    'Micropterus salmoides',
    'Largemouth bass',
    'Centrarchidae',
    'fish',
    'fusiform',
    [30, 60],
    'olive',
    'stripe',
    'littoral',
    0,
    [18, 30],
    'LC',
  ],
  [
    'Micropterus dolomieu',
    'Smallmouth bass',
    'Centrarchidae',
    'fish',
    'fusiform',
    [28, 50],
    'bronze',
    'bars',
    'littoral',
    0,
    [15, 26],
    'LC',
  ],
  [
    'Micropterus punctulatus',
    'Spotted bass',
    'Centrarchidae',
    'fish',
    'fusiform',
    [25, 45],
    'olive',
    'spots',
    'littoral',
    0,
    [18, 28],
    'LC',
  ],
  [
    'Lepomis macrochirus',
    'Bluegill',
    'Centrarchidae',
    'fish',
    'compressed',
    [12, 25],
    'sunny',
    'bars',
    'littoral',
    1,
    [18, 30],
    'LC',
  ],
  [
    'Lepomis gibbosus',
    'Pumpkinseed',
    'Centrarchidae',
    'fish',
    'compressed',
    [10, 20],
    'ember',
    'spots',
    'littoral',
    1,
    [16, 28],
    'LC',
  ],
  [
    'Lepomis cyanellus',
    'Green sunfish',
    'Centrarchidae',
    'fish',
    'compressed',
    [10, 20],
    'olive',
    'bars',
    'littoral',
    1,
    [18, 30],
    'LC',
  ],
  [
    'Lepomis megalotis',
    'Longear sunfish',
    'Centrarchidae',
    'fish',
    'compressed',
    [10, 18],
    'ember',
    'mottled',
    'littoral',
    1,
    [18, 28],
    'LC',
  ],
  [
    'Lepomis microlophus',
    'Redear sunfish',
    'Centrarchidae',
    'fish',
    'compressed',
    [15, 28],
    'gold',
    'none',
    'littoral',
    1,
    [20, 30],
    'LC',
  ],
  [
    'Lepomis auritus',
    'Redbreast sunfish',
    'Centrarchidae',
    'fish',
    'compressed',
    [12, 22],
    'ember',
    'none',
    'littoral',
    1,
    [18, 28],
    'LC',
  ],
  [
    'Lepomis gulosus',
    'Warmouth',
    'Centrarchidae',
    'fish',
    'compressed',
    [12, 22],
    'mud',
    'mottled',
    'littoral',
    0,
    [20, 30],
    'LC',
  ],
  [
    'Ambloplites rupestris',
    'Rock bass',
    'Centrarchidae',
    'fish',
    'compressed',
    [15, 25],
    'bronze',
    'spots',
    'littoral',
    0,
    [16, 26],
    'LC',
  ],
  [
    'Pomoxis nigromaculatus',
    'Black crappie',
    'Centrarchidae',
    'fish',
    'compressed',
    [18, 30],
    'silver',
    'mottled',
    'midwater',
    1,
    [15, 26],
    'LC',
  ],
  [
    'Pomoxis annularis',
    'White crappie',
    'Centrarchidae',
    'fish',
    'compressed',
    [18, 30],
    'silver',
    'bars',
    'midwater',
    1,
    [15, 26],
    'LC',
  ],
  // Percidae
  [
    'Perca flavescens',
    'Yellow perch',
    'Percidae',
    'fish',
    'fusiform',
    [15, 30],
    'gold',
    'bars',
    'midwater',
    1,
    [12, 24],
    'LC',
  ],
  [
    'Sander vitreus',
    'Walleye',
    'Percidae',
    'fish',
    'fusiform',
    [40, 70],
    'bronze',
    'mottled',
    'midwater',
    0,
    [12, 22],
    'LC',
  ],
  [
    'Sander canadensis',
    'Sauger',
    'Percidae',
    'fish',
    'fusiform',
    [30, 45],
    'mud',
    'spots',
    'benthic',
    0,
    [12, 22],
    'LC',
  ],
  [
    'Percina caprodes',
    'Logperch',
    'Percidae',
    'fish',
    'small',
    [8, 14],
    'darter',
    'bars',
    'benthic',
    0,
    [10, 22],
    'LC',
  ],
  [
    'Etheostoma nigrum',
    'Johnny darter',
    'Percidae',
    'fish',
    'small',
    [4, 7],
    'darter',
    'spots',
    'benthic',
    0,
    [10, 22],
    'LC',
  ],
  [
    'Etheostoma flabellare',
    'Fantail darter',
    'Percidae',
    'fish',
    'small',
    [4, 8],
    'darter',
    'bars',
    'benthic',
    0,
    [8, 20],
    'LC',
  ],
  // Esocidae
  [
    'Esox lucius',
    'Northern pike',
    'Esocidae',
    'fish',
    'elongate',
    [50, 90],
    'pike',
    'spots',
    'littoral',
    0,
    [10, 22],
    'LC',
  ],
  [
    'Esox masquinongy',
    'Muskellunge',
    'Esocidae',
    'fish',
    'elongate',
    [80, 130],
    'pike',
    'bars',
    'littoral',
    0,
    [12, 24],
    'LC',
  ],
  [
    'Esox niger',
    'Chain pickerel',
    'Esocidae',
    'fish',
    'elongate',
    [35, 60],
    'pike',
    'mottled',
    'littoral',
    0,
    [12, 26],
    'LC',
  ],
  [
    'Esox americanus',
    'Grass pickerel',
    'Esocidae',
    'fish',
    'elongate',
    [20, 35],
    'pike',
    'bars',
    'littoral',
    0,
    [12, 26],
    'LC',
  ],
  // Salmonidae and relatives
  [
    'Oncorhynchus mykiss',
    'Rainbow trout',
    'Salmonidae',
    'fish',
    'fusiform',
    [30, 60],
    'rainbow',
    'spots',
    'midwater',
    0,
    [8, 18],
    'LC',
  ],
  [
    'Salmo trutta',
    'Brown trout',
    'Salmonidae',
    'fish',
    'fusiform',
    [30, 60],
    'brown',
    'spots',
    'midwater',
    0,
    [8, 18],
    'LC',
  ],
  [
    'Salvelinus namaycush',
    'Lake trout',
    'Salmonidae',
    'fish',
    'fusiform',
    [45, 80],
    'lake',
    'spots',
    'benthic',
    0,
    [4, 12],
    'LC',
  ],
  [
    'Salvelinus fontinalis',
    'Brook trout',
    'Salmonidae',
    'fish',
    'fusiform',
    [20, 40],
    'char',
    'mottled',
    'midwater',
    0,
    [6, 16],
    'LC',
  ],
  [
    'Oncorhynchus tshawytscha',
    'Chinook salmon',
    'Salmonidae',
    'fish',
    'fusiform',
    [60, 100],
    'steel',
    'spots',
    'midwater',
    0,
    [6, 16],
    'NT',
  ],
  [
    'Oncorhynchus nerka',
    'Kokanee salmon',
    'Salmonidae',
    'fish',
    'fusiform',
    [25, 40],
    'salmon',
    'none',
    'midwater',
    1,
    [6, 14],
    'LC',
  ],
  [
    'Oncorhynchus kisutch',
    'Coho salmon',
    'Salmonidae',
    'fish',
    'fusiform',
    [50, 80],
    'steel',
    'spots',
    'midwater',
    0,
    [6, 16],
    'LC',
  ],
  [
    'Salmo salar',
    'Atlantic salmon',
    'Salmonidae',
    'fish',
    'fusiform',
    [55, 90],
    'steel',
    'spots',
    'midwater',
    0,
    [6, 16],
    'LC',
  ],
  [
    'Oncorhynchus clarkii',
    'Cutthroat trout',
    'Salmonidae',
    'fish',
    'fusiform',
    [30, 55],
    'bronze',
    'spots',
    'midwater',
    0,
    [6, 16],
    'LC',
  ],
  [
    'Coregonus clupeaformis',
    'Lake whitefish',
    'Salmonidae',
    'fish',
    'fusiform',
    [35, 60],
    'silver',
    'none',
    'benthic',
    1,
    [6, 14],
    'LC',
  ],
  [
    'Coregonus artedi',
    'Cisco',
    'Salmonidae',
    'fish',
    'fusiform',
    [25, 40],
    'shad',
    'none',
    'midwater',
    1,
    [4, 12],
    'LC',
  ],
  [
    'Prosopium williamsoni',
    'Mountain whitefish',
    'Salmonidae',
    'fish',
    'fusiform',
    [25, 45],
    'silver',
    'none',
    'benthic',
    1,
    [4, 14],
    'LC',
  ],
  [
    'Osmerus mordax',
    'Rainbow smelt',
    'Osmeridae',
    'fish',
    'fusiform',
    [12, 22],
    'shad',
    'none',
    'midwater',
    1,
    [4, 14],
    'LC',
  ],
  // Ictaluridae
  [
    'Ictalurus punctatus',
    'Channel catfish',
    'Ictaluridae',
    'fish',
    'benthic',
    [40, 80],
    'catfish',
    'spots',
    'benthic',
    0,
    [18, 30],
    'LC',
  ],
  [
    'Ictalurus furcatus',
    'Blue catfish',
    'Ictaluridae',
    'fish',
    'benthic',
    [50, 110],
    'steel',
    'none',
    'benthic',
    0,
    [18, 30],
    'LC',
  ],
  [
    'Pylodictis olivaris',
    'Flathead catfish',
    'Ictaluridae',
    'fish',
    'benthic',
    [50, 100],
    'mud',
    'mottled',
    'benthic',
    0,
    [18, 30],
    'LC',
  ],
  [
    'Ameiurus nebulosus',
    'Brown bullhead',
    'Ictaluridae',
    'fish',
    'benthic',
    [20, 35],
    'mud',
    'mottled',
    'benthic',
    0,
    [16, 28],
    'LC',
  ],
  [
    'Ameiurus melas',
    'Black bullhead',
    'Ictaluridae',
    'fish',
    'benthic',
    [20, 35],
    'slate',
    'none',
    'benthic',
    0,
    [16, 28],
    'LC',
  ],
  [
    'Noturus gyrinus',
    'Tadpole madtom',
    'Ictaluridae',
    'fish',
    'small',
    [5, 10],
    'mud',
    'none',
    'benthic',
    0,
    [14, 26],
    'LC',
  ],
  // Cyprinidae and minnows
  [
    'Cyprinus carpio',
    'Common carp',
    'Cyprinidae',
    'fish',
    'benthic',
    [40, 80],
    'carp',
    'none',
    'benthic',
    0,
    [16, 30],
    'VU',
  ],
  [
    'Carassius auratus',
    'Goldfish',
    'Cyprinidae',
    'fish',
    'benthic',
    [12, 25],
    'gold',
    'none',
    'littoral',
    0,
    [14, 28],
    'LC',
  ],
  [
    'Ctenopharyngodon idella',
    'Grass carp',
    'Cyprinidae',
    'fish',
    'fusiform',
    [60, 100],
    'olive',
    'none',
    'littoral',
    0,
    [16, 28],
    'LC',
  ],
  [
    'Hypophthalmichthys nobilis',
    'Bighead carp',
    'Cyprinidae',
    'fish',
    'benthic',
    [60, 100],
    'slate',
    'mottled',
    'surface',
    0,
    [16, 28],
    'DD',
  ],
  [
    'Hypophthalmichthys molitrix',
    'Silver carp',
    'Cyprinidae',
    'fish',
    'compressed',
    [50, 90],
    'silver',
    'none',
    'surface',
    1,
    [16, 28],
    'NT',
  ],
  [
    'Notemigonus crysoleucas',
    'Golden shiner',
    'Leuciscidae',
    'fish',
    'compressed',
    [8, 15],
    'gold',
    'none',
    'littoral',
    1,
    [14, 28],
    'LC',
  ],
  [
    'Pimephales promelas',
    'Fathead minnow',
    'Leuciscidae',
    'fish',
    'small',
    [5, 9],
    'dace',
    'none',
    'littoral',
    1,
    [14, 28],
    'LC',
  ],
  [
    'Pimephales notatus',
    'Bluntnose minnow',
    'Leuciscidae',
    'fish',
    'small',
    [5, 9],
    'dace',
    'stripe',
    'littoral',
    1,
    [14, 28],
    'LC',
  ],
  [
    'Notropis atherinoides',
    'Emerald shiner',
    'Leuciscidae',
    'fish',
    'small',
    [6, 10],
    'shad',
    'none',
    'midwater',
    1,
    [12, 26],
    'LC',
  ],
  [
    'Notropis hudsonius',
    'Spottail shiner',
    'Leuciscidae',
    'fish',
    'small',
    [6, 11],
    'shad',
    'spots',
    'littoral',
    1,
    [12, 24],
    'LC',
  ],
  [
    'Luxilus cornutus',
    'Common shiner',
    'Leuciscidae',
    'fish',
    'small',
    [7, 12],
    'dace',
    'none',
    'littoral',
    1,
    [12, 24],
    'LC',
  ],
  [
    'Cyprinella spiloptera',
    'Spotfin shiner',
    'Leuciscidae',
    'fish',
    'small',
    [6, 10],
    'shad',
    'spots',
    'littoral',
    1,
    [14, 28],
    'LC',
  ],
  [
    'Semotilus atromaculatus',
    'Creek chub',
    'Leuciscidae',
    'fish',
    'small',
    [10, 18],
    'dace',
    'spots',
    'littoral',
    0,
    [10, 24],
    'LC',
  ],
  [
    'Rhinichthys atratulus',
    'Blacknose dace',
    'Leuciscidae',
    'fish',
    'small',
    [5, 9],
    'dace',
    'stripe',
    'benthic',
    1,
    [8, 20],
    'LC',
  ],
  [
    'Couesius plumbeus',
    'Lake chub',
    'Leuciscidae',
    'fish',
    'small',
    [8, 14],
    'silver',
    'none',
    'littoral',
    1,
    [6, 18],
    'LC',
  ],
  [
    'Richardsonius egregius',
    'Lahontan redside',
    'Leuciscidae',
    'fish',
    'small',
    [8, 14],
    'dace',
    'stripe',
    'littoral',
    1,
    [10, 22],
    'LC',
  ],
  [
    'Siphateles bicolor',
    'Tui chub',
    'Leuciscidae',
    'fish',
    'compressed',
    [15, 30],
    'mud',
    'none',
    'littoral',
    1,
    [10, 22],
    'LC',
  ],
  [
    'Chrosomus eos',
    'Northern redbelly dace',
    'Leuciscidae',
    'fish',
    'small',
    [4, 8],
    'dace',
    'stripe',
    'littoral',
    1,
    [8, 20],
    'LC',
  ],
  // Catostomidae
  [
    'Catostomus commersonii',
    'White sucker',
    'Catostomidae',
    'fish',
    'benthic',
    [25, 45],
    'mud',
    'none',
    'benthic',
    0,
    [8, 22],
    'LC',
  ],
  [
    'Catostomus catostomus',
    'Longnose sucker',
    'Catostomidae',
    'fish',
    'benthic',
    [25, 45],
    'slate',
    'none',
    'benthic',
    0,
    [4, 16],
    'LC',
  ],
  [
    'Catostomus tahoensis',
    'Tahoe sucker',
    'Catostomidae',
    'fish',
    'benthic',
    [25, 45],
    'mud',
    'none',
    'benthic',
    0,
    [8, 20],
    'LC',
  ],
  [
    'Moxostoma macrolepidotum',
    'Shorthead redhorse',
    'Catostomidae',
    'fish',
    'benthic',
    [30, 55],
    'bronze',
    'none',
    'benthic',
    0,
    [12, 24],
    'LC',
  ],
  [
    'Ictiobus cyprinellus',
    'Bigmouth buffalo',
    'Catostomidae',
    'fish',
    'benthic',
    [40, 80],
    'mud',
    'none',
    'benthic',
    0,
    [16, 28],
    'LC',
  ],
  // Gars, bowfin, sturgeons
  [
    'Lepisosteus osseus',
    'Longnose gar',
    'Lepisosteidae',
    'fish',
    'elongate',
    [70, 130],
    'gar',
    'spots',
    'surface',
    0,
    [16, 30],
    'LC',
  ],
  [
    'Lepisosteus oculatus',
    'Spotted gar',
    'Lepisosteidae',
    'fish',
    'elongate',
    [50, 80],
    'gar',
    'spots',
    'surface',
    0,
    [16, 30],
    'LC',
  ],
  [
    'Amia calva',
    'Bowfin',
    'Amiidae',
    'fish',
    'elongate',
    [45, 70],
    'olive',
    'mottled',
    'littoral',
    0,
    [16, 30],
    'LC',
  ],
  [
    'Acipenser fulvescens',
    'Lake sturgeon',
    'Acipenseridae',
    'fish',
    'benthic',
    [100, 180],
    'sturgeon',
    'none',
    'benthic',
    0,
    [8, 20],
    'EN',
  ],
  [
    'Acipenser oxyrinchus',
    'Atlantic sturgeon',
    'Acipenseridae',
    'fish',
    'benthic',
    [120, 250],
    'sturgeon',
    'none',
    'benthic',
    0,
    [8, 24],
    'NT',
  ],
  [
    'Scaphirhynchus platorynchus',
    'Shovelnose sturgeon',
    'Acipenseridae',
    'fish',
    'benthic',
    [60, 100],
    'sturgeon',
    'none',
    'benthic',
    0,
    [8, 24],
    'NT',
  ],
  // Herrings, shads
  [
    'Alosa sapidissima',
    'American shad',
    'Clupeidae',
    'fish',
    'compressed',
    [35, 60],
    'shad',
    'spots',
    'midwater',
    1,
    [8, 20],
    'LC',
  ],
  [
    'Alosa pseudoharengus',
    'Alewife',
    'Clupeidae',
    'fish',
    'compressed',
    [15, 28],
    'shad',
    'spots',
    'midwater',
    1,
    [8, 22],
    'LC',
  ],
  [
    'Alosa aestivalis',
    'Blueback herring',
    'Clupeidae',
    'fish',
    'compressed',
    [20, 30],
    'shad',
    'none',
    'midwater',
    1,
    [8, 22],
    'LC',
  ],
  [
    'Dorosoma cepedianum',
    'Gizzard shad',
    'Clupeidae',
    'fish',
    'compressed',
    [20, 38],
    'shad',
    'spots',
    'midwater',
    1,
    [12, 28],
    'LC',
  ],
  // Eels and lampreys
  [
    'Anguilla rostrata',
    'American eel',
    'Anguillidae',
    'fish',
    'anguilliform',
    [50, 100],
    'eel',
    'none',
    'benthic',
    0,
    [8, 26],
    'EN',
  ],
  [
    'Petromyzon marinus',
    'Sea lamprey',
    'Petromyzontidae',
    'lamprey',
    'anguilliform',
    [40, 80],
    'lamprey',
    'mottled',
    'benthic',
    0,
    [6, 20],
    'LC',
  ],
  [
    'Ichthyomyzon unicuspis',
    'Silver lamprey',
    'Petromyzontidae',
    'lamprey',
    'anguilliform',
    [20, 38],
    'lamprey',
    'none',
    'benthic',
    0,
    [6, 20],
    'LC',
  ],
  [
    'Lethenteron appendix',
    'American brook lamprey',
    'Petromyzontidae',
    'lamprey',
    'anguilliform',
    [10, 20],
    'lamprey',
    'none',
    'benthic',
    0,
    [6, 20],
    'LC',
  ],
  // Temperate basses and misc
  [
    'Morone saxatilis',
    'Striped bass',
    'Moronidae',
    'fish',
    'fusiform',
    [50, 110],
    'striper',
    'stripe',
    'midwater',
    0,
    [10, 24],
    'LC',
  ],
  [
    'Morone americana',
    'White perch',
    'Moronidae',
    'fish',
    'compressed',
    [15, 28],
    'silver',
    'none',
    'midwater',
    1,
    [10, 26],
    'LC',
  ],
  [
    'Morone chrysops',
    'White bass',
    'Moronidae',
    'fish',
    'compressed',
    [25, 40],
    'silver',
    'stripe',
    'midwater',
    1,
    [14, 26],
    'LC',
  ],
  [
    'Aplodinotus grunniens',
    'Freshwater drum',
    'Sciaenidae',
    'fish',
    'benthic',
    [30, 60],
    'drum',
    'none',
    'benthic',
    0,
    [14, 28],
    'LC',
  ],
  [
    'Percopsis omiscomaycus',
    'Trout-perch',
    'Percopsidae',
    'fish',
    'small',
    [8, 14],
    'silver',
    'spots',
    'benthic',
    1,
    [6, 18],
    'LC',
  ],
  [
    'Lota lota',
    'Burbot',
    'Lotidae',
    'fish',
    'elongate',
    [35, 70],
    'mud',
    'mottled',
    'benthic',
    0,
    [2, 12],
    'LC',
  ],
  [
    'Gasterosteus aculeatus',
    'Threespine stickleback',
    'Gasterosteidae',
    'fish',
    'small',
    [4, 8],
    'stickleback',
    'none',
    'littoral',
    1,
    [6, 20],
    'LC',
  ],
  [
    'Culaea inconstans',
    'Brook stickleback',
    'Gasterosteidae',
    'fish',
    'small',
    [4, 7],
    'stickleback',
    'mottled',
    'littoral',
    1,
    [6, 20],
    'LC',
  ],
  [
    'Fundulus diaphanus',
    'Banded killifish',
    'Fundulidae',
    'fish',
    'small',
    [5, 9],
    'killifish',
    'bars',
    'surface',
    1,
    [12, 26],
    'LC',
  ],
  [
    'Fundulus heteroclitus',
    'Mummichog',
    'Fundulidae',
    'fish',
    'small',
    [6, 10],
    'killifish',
    'spots',
    'surface',
    1,
    [10, 28],
    'LC',
  ],
  [
    'Menidia menidia',
    'Atlantic silverside',
    'Atherinopsidae',
    'fish',
    'small',
    [6, 12],
    'shad',
    'stripe',
    'surface',
    1,
    [8, 26],
    'LC',
  ],
  [
    'Labidesthes sicculus',
    'Brook silverside',
    'Atherinopsidae',
    'fish',
    'small',
    [6, 9],
    'shad',
    'stripe',
    'surface',
    1,
    [14, 28],
    'LC',
  ],
  [
    'Gambusia affinis',
    'Western mosquitofish',
    'Poeciliidae',
    'fish',
    'small',
    [3, 6],
    'killifish',
    'none',
    'surface',
    1,
    [16, 32],
    'LC',
  ],
  [
    'Neogobius melanostomus',
    'Round goby',
    'Gobiidae',
    'fish',
    'small',
    [8, 18],
    'sculpin',
    'mottled',
    'benthic',
    0,
    [8, 24],
    'LC',
  ],
  [
    'Cottus bairdii',
    'Mottled sculpin',
    'Cottidae',
    'fish',
    'small',
    [6, 11],
    'sculpin',
    'mottled',
    'benthic',
    0,
    [6, 18],
    'LC',
  ],
  [
    'Cottus cognatus',
    'Slimy sculpin',
    'Cottidae',
    'fish',
    'small',
    [5, 10],
    'sculpin',
    'mottled',
    'benthic',
    0,
    [4, 14],
    'LC',
  ],
  [
    'Umbra limi',
    'Central mudminnow',
    'Umbridae',
    'fish',
    'small',
    [5, 10],
    'mud',
    'stripe',
    'benthic',
    0,
    [8, 24],
    'LC',
  ],
  [
    'Mugil cephalus',
    'Striped mullet',
    'Mugilidae',
    'fish',
    'fusiform',
    [25, 50],
    'silver',
    'stripe',
    'surface',
    1,
    [14, 30],
    'LC',
  ],
  [
    'Channa argus',
    'Northern snakehead',
    'Channidae',
    'fish',
    'elongate',
    [40, 80],
    'mud',
    'mottled',
    'littoral',
    0,
    [12, 28],
    'LC',
  ],
  // Turtles
  [
    'Chelydra serpentina',
    'Snapping turtle',
    'Chelydridae',
    'turtle',
    'turtle',
    [20, 40],
    'turtleB',
    'none',
    'benthic',
    0,
    undefined,
    'LC',
  ],
  [
    'Chrysemys picta',
    'Painted turtle',
    'Emydidae',
    'turtle',
    'turtle',
    [12, 20],
    'turtleP',
    'stripe',
    'surface',
    0,
    undefined,
    'LC',
  ],
  [
    'Trachemys scripta',
    'Red-eared slider',
    'Emydidae',
    'turtle',
    'turtle',
    [15, 28],
    'turtleG',
    'stripe',
    'surface',
    0,
    undefined,
    'LC',
  ],
  [
    'Graptemys geographica',
    'Northern map turtle',
    'Emydidae',
    'turtle',
    'turtle',
    [15, 27],
    'turtleG',
    'mottled',
    'surface',
    0,
    undefined,
    'LC',
  ],
  [
    'Sternotherus odoratus',
    'Eastern musk turtle',
    'Kinosternidae',
    'turtle',
    'turtle',
    [8, 13],
    'turtleB',
    'none',
    'benthic',
    0,
    undefined,
    'LC',
  ],
  [
    'Apalone spinifera',
    'Spiny softshell',
    'Trionychidae',
    'turtle',
    'turtle',
    [18, 45],
    'turtleB',
    'spots',
    'littoral',
    0,
    undefined,
    'LC',
  ],
  [
    'Emydoidea blandingii',
    "Blanding's turtle",
    'Emydidae',
    'turtle',
    'turtle',
    [15, 27],
    'turtleP',
    'spots',
    'surface',
    0,
    undefined,
    'EN',
  ],
  [
    'Malaclemys terrapin',
    'Diamondback terrapin',
    'Emydidae',
    'turtle',
    'turtle',
    [13, 23],
    'turtleG',
    'mottled',
    'surface',
    0,
    undefined,
    'VU',
  ],
  // Amphibians
  [
    'Lithobates catesbeianus',
    'American bullfrog',
    'Ranidae',
    'amphibian',
    'frog',
    [9, 15],
    'bullfrog',
    'mottled',
    'surface',
    0,
    undefined,
    'LC',
  ],
  [
    'Lithobates clamitans',
    'Green frog',
    'Ranidae',
    'amphibian',
    'frog',
    [6, 10],
    'frog',
    'none',
    'surface',
    0,
    undefined,
    'LC',
  ],
  [
    'Lithobates pipiens',
    'Northern leopard frog',
    'Ranidae',
    'amphibian',
    'frog',
    [5, 9],
    'leopard',
    'spots',
    'surface',
    0,
    undefined,
    'LC',
  ],
  [
    'Notophthalmus viridescens',
    'Eastern newt',
    'Salamandridae',
    'amphibian',
    'frog',
    [6, 10],
    'newt',
    'spots',
    'littoral',
    0,
    undefined,
    'LC',
  ],
  [
    'Taricha granulosa',
    'Rough-skinned newt',
    'Salamandridae',
    'amphibian',
    'frog',
    [12, 20],
    'newt',
    'none',
    'littoral',
    0,
    undefined,
    'LC',
  ],
  [
    'Necturus maculosus',
    'Mudpuppy',
    'Proteidae',
    'amphibian',
    'frog',
    [20, 35],
    'mud',
    'spots',
    'benthic',
    0,
    undefined,
    'LC',
  ],
  // Crustaceans
  [
    'Faxonius rusticus',
    'Rusty crayfish',
    'Cambaridae',
    'crustacean',
    'crayfish',
    [7, 12],
    'crayR',
    'spots',
    'benthic',
    0,
    undefined,
    'LC',
  ],
  [
    'Faxonius limosus',
    'Spinycheek crayfish',
    'Cambaridae',
    'crustacean',
    'crayfish',
    [6, 10],
    'crayG',
    'none',
    'benthic',
    0,
    undefined,
    'LC',
  ],
  [
    'Faxonius virilis',
    'Virile crayfish',
    'Cambaridae',
    'crustacean',
    'crayfish',
    [7, 12],
    'crayO',
    'none',
    'benthic',
    0,
    undefined,
    'LC',
  ],
  [
    'Procambarus clarkii',
    'Red swamp crayfish',
    'Cambaridae',
    'crustacean',
    'crayfish',
    [8, 12],
    'crayR',
    'none',
    'benthic',
    0,
    undefined,
    'LC',
  ],
  [
    'Pacifastacus leniusculus',
    'Signal crayfish',
    'Astacidae',
    'crustacean',
    'crayfish',
    [8, 15],
    'crayO',
    'none',
    'benthic',
    0,
    undefined,
    'LC',
  ],
  [
    'Callinectes sapidus',
    'Blue crab',
    'Portunidae',
    'crustacean',
    'crab',
    [12, 23],
    'crabB',
    'none',
    'benthic',
    0,
    undefined,
    'LC',
  ],
  [
    'Carcinus maenas',
    'European green crab',
    'Carcinidae',
    'crustacean',
    'crab',
    [5, 9],
    'crabG',
    'mottled',
    'benthic',
    0,
    undefined,
    'LC',
  ],
  [
    'Hemigrapsus sanguineus',
    'Asian shore crab',
    'Varunidae',
    'crustacean',
    'crab',
    [3, 5],
    'crabG',
    'bars',
    'benthic',
    0,
    undefined,
    'LC',
  ],
  [
    'Eriocheir sinensis',
    'Chinese mitten crab',
    'Varunidae',
    'crustacean',
    'crab',
    [5, 8],
    'crabG',
    'none',
    'benthic',
    0,
    undefined,
    'LC',
  ],
  // Molluscs
  [
    'Dreissena polymorpha',
    'Zebra mussel',
    'Dreissenidae',
    'mollusc',
    'mussel',
    [1.5, 3],
    'musselZ',
    'bars',
    'benthic',
    1,
    undefined,
    'LC',
  ],
  [
    'Dreissena bugensis',
    'Quagga mussel',
    'Dreissenidae',
    'mollusc',
    'mussel',
    [1.5, 3.5],
    'musselZ',
    'bars',
    'benthic',
    1,
    undefined,
    'LC',
  ],
  [
    'Corbicula fluminea',
    'Asian clam',
    'Cyrenidae',
    'mollusc',
    'mussel',
    [1.5, 4],
    'clam',
    'none',
    'benthic',
    1,
    undefined,
    'LC',
  ],
  [
    'Elliptio complanata',
    'Eastern elliptio',
    'Unionidae',
    'mollusc',
    'mussel',
    [7, 12],
    'mussel',
    'none',
    'benthic',
    0,
    undefined,
    'LC',
  ],
  [
    'Lampsilis siliquoidea',
    'Fatmucket',
    'Unionidae',
    'mollusc',
    'mussel',
    [8, 12],
    'clam',
    'stripe',
    'benthic',
    0,
    undefined,
    'LC',
  ],
  [
    'Pyganodon grandis',
    'Giant floater',
    'Unionidae',
    'mollusc',
    'mussel',
    [10, 18],
    'clam',
    'none',
    'benthic',
    0,
    undefined,
    'LC',
  ],
  [
    'Amblema plicata',
    'Threeridge',
    'Unionidae',
    'mollusc',
    'mussel',
    [8, 14],
    'mussel',
    'bars',
    'benthic',
    0,
    undefined,
    'LC',
  ],
  [
    'Crassostrea virginica',
    'Eastern oyster',
    'Ostreidae',
    'mollusc',
    'mussel',
    [7, 12],
    'oyster',
    'none',
    'benthic',
    1,
    undefined,
    'LC',
  ],
  [
    'Potamopyrgus antipodarum',
    'New Zealand mudsnail',
    'Tateidae',
    'mollusc',
    'mussel',
    [0.4, 0.6],
    'snail',
    'none',
    'benthic',
    1,
    undefined,
    'LC',
  ],
  [
    'Bithynia tentaculata',
    'Faucet snail',
    'Bithyniidae',
    'mollusc',
    'mussel',
    [0.8, 1.5],
    'snail',
    'none',
    'benthic',
    1,
    undefined,
    'LC',
  ],
  // Mammals
  [
    'Castor canadensis',
    'North American beaver',
    'Castoridae',
    'mammal',
    'mammal',
    [80, 110],
    'mammalB',
    'none',
    'surface',
    0,
    undefined,
    'LC',
  ],
  [
    'Ondatra zibethicus',
    'Muskrat',
    'Cricetidae',
    'mammal',
    'mammal',
    [40, 60],
    'mammalO',
    'none',
    'surface',
    0,
    undefined,
    'LC',
  ],
  [
    'Lontra canadensis',
    'North American river otter',
    'Mustelidae',
    'mammal',
    'mammal',
    [90, 130],
    'mammalO',
    'none',
    'surface',
    0,
    undefined,
    'LC',
  ],
  [
    'Trichechus manatus',
    'West Indian manatee',
    'Trichechidae',
    'mammal',
    'mammal',
    [250, 350],
    'mammalG',
    'none',
    'midwater',
    0,
    undefined,
    'VU',
  ],
  [
    'Phoca vitulina',
    'Harbor seal',
    'Phocidae',
    'mammal',
    'mammal',
    [140, 190],
    'mammalG',
    'spots',
    'surface',
    0,
    undefined,
    'LC',
  ],
  [
    'Tursiops truncatus',
    'Common bottlenose dolphin',
    'Delphinidae',
    'mammal',
    'mammal',
    [250, 380],
    'mammalG',
    'none',
    'midwater',
    0,
    undefined,
    'LC',
  ],
  // Plants
  [
    'Nymphaea odorata',
    'American white water lily',
    'Nymphaeaceae',
    'plant',
    'plant',
    [30, 60],
    'plantL',
    'none',
    'littoral',
    0,
    undefined,
    'LC',
  ],
  [
    'Nuphar lutea',
    'Yellow pond-lily',
    'Nymphaeaceae',
    'plant',
    'plant',
    [30, 70],
    'plantY',
    'none',
    'littoral',
    0,
    undefined,
    'LC',
  ],
  [
    'Potamogeton crispus',
    'Curly-leaf pondweed',
    'Potamogetonaceae',
    'plant',
    'plant',
    [40, 120],
    'plantM',
    'none',
    'littoral',
    0,
    undefined,
    'LC',
  ],
  [
    'Stuckenia pectinata',
    'Sago pondweed',
    'Potamogetonaceae',
    'plant',
    'plant',
    [40, 150],
    'plantM',
    'none',
    'littoral',
    0,
    undefined,
    'LC',
  ],
  [
    'Myriophyllum spicatum',
    'Eurasian watermilfoil',
    'Haloragaceae',
    'plant',
    'plant',
    [60, 250],
    'plantG',
    'none',
    'littoral',
    0,
    undefined,
    'LC',
  ],
  [
    'Vallisneria americana',
    'American wild celery',
    'Hydrocharitaceae',
    'plant',
    'plant',
    [40, 120],
    'plantG',
    'none',
    'littoral',
    0,
    undefined,
    'LC',
  ],
  [
    'Elodea canadensis',
    'Canadian waterweed',
    'Hydrocharitaceae',
    'plant',
    'plant',
    [30, 100],
    'plantG',
    'none',
    'littoral',
    0,
    undefined,
    'LC',
  ],
  [
    'Hydrilla verticillata',
    'Hydrilla',
    'Hydrocharitaceae',
    'plant',
    'plant',
    [60, 300],
    'plantG',
    'none',
    'littoral',
    0,
    undefined,
    'LC',
  ],
  [
    'Ceratophyllum demersum',
    'Coontail',
    'Ceratophyllaceae',
    'plant',
    'plant',
    [50, 200],
    'plantM',
    'none',
    'littoral',
    0,
    undefined,
    'LC',
  ],
  [
    'Typha latifolia',
    'Broadleaf cattail',
    'Typhaceae',
    'plant',
    'plant',
    [150, 250],
    'plantY',
    'none',
    'littoral',
    0,
    undefined,
    'LC',
  ],
  [
    'Typha angustifolia',
    'Narrowleaf cattail',
    'Typhaceae',
    'plant',
    'plant',
    [150, 250],
    'plantY',
    'none',
    'littoral',
    0,
    undefined,
    'LC',
  ],
  [
    'Trapa natans',
    'European water chestnut',
    'Lythraceae',
    'plant',
    'plant',
    [50, 150],
    'plantG',
    'none',
    'surface',
    0,
    undefined,
    'LC',
  ],
  [
    'Najas flexilis',
    'Slender naiad',
    'Hydrocharitaceae',
    'plant',
    'plant',
    [20, 80],
    'plantM',
    'none',
    'littoral',
    0,
    undefined,
    'LC',
  ],
  // Cyanobacteria (shown as suspended specks, not as actors)
  [
    'Microcystis aeruginosa',
    'Microcystis (blue-green alga)',
    'Microcystaceae',
    'cyanobacteria',
    'plant',
    [0.0005, 0.001],
    'algae',
    'none',
    'surface',
    1,
    undefined,
    'LC',
  ],
  [
    'Dolichospermum flosaquae',
    'Dolichospermum (blue-green alga)',
    'Nostocaceae',
    'cyanobacteria',
    'plant',
    [0.0005, 0.002],
    'algae',
    'none',
    'surface',
    1,
    undefined,
    'LC',
  ],
];

const slug = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

const catalog: CatalogSpecies[] = ROWS.map(
  ([sci, common, family, group, archetype, len, pal, pattern, band, school, temp, iucn, notes]) => {
    const [back, side, belly, fin] = PAL[pal];
    const entry: CatalogSpecies = {
      id: slug(sci),
      scientificName: sci,
      commonName: common,
      archetype,
      lengthCm: len,
      colors: { back, side, belly, fin, pattern },
      depthBand: band,
      schooling: school === 1,
      group,
      family,
    };
    if (temp) entry.tempPrefC = temp;
    if (iucn) entry.iucn = iucn;
    if (notes) entry.notes = notes;
    return entry;
  },
);

const ids = new Set<string>();
for (const c of catalog) {
  if (ids.has(c.id)) throw new Error(`duplicate catalog id ${c.id}`);
  ids.add(c.id);
}

const here = dirname(fileURLToPath(import.meta.url));
writeFileSync(join(here, '..', 'species-catalog.json'), JSON.stringify(catalog, null, 1) + '\n');
console.log(`wrote ${catalog.length} species`);
